### ISSUE TITLE
(+) icon for tools need same with add exercise

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#88]
can you please change the add icon on the tools to the same as the articles and exercises (green circle with white "+").

![image](https://user-images.githubusercontent.com/8002065/34190153-d2717308-e571-11e7-82a7-23b382918ed6.png)

![image](https://user-images.githubusercontent.com/8002065/34190172-e2b29dc8-e571-11e7-818e-ede4908a8bbf.png)

**Comment by divppc** [comment]
done 
![image](https://user-images.githubusercontent.com/18699015/34199485-9cffe40c-e576-11e7-962b-0e395065c039.png)

**Comment by sonit1810** [comment]
Thanks Ihor,

Justin asked one more 💃 , he need hover

"can you also please change the "+" symbol for tools so that it is hover effect like we have for adding articles and adding exercises"

**Comment by divppc** [comment]
done http://physio.div.agency/card.html

**Comment by sonit1810** [comment]
Hi Ihor,

You forgot push code for this changes ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by divppc** [comment]
Hi Sonit.

I just waiting for another changes from Justin. Now repo is updated
